steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=app/backend/Dockerfile
      - --tag=asia-northeast3-docker.pkg.dev/$PROJECT_ID/banghub/backend:${_IMAGE_TAG}
      - .
images:
  - asia-northeast3-docker.pkg.dev/$PROJECT_ID/banghub/backend:${_IMAGE_TAG}
options:
  logging: CLOUD_LOGGING_ONLY
